package com.i.common.attendance.network.response
import com.google.gson.JsonElement
import com.google.gson.annotations.SerializedName


data class LedgerPdfDataShowResponse (
  @SerializedName("status"  ) var status  : String?           = null,
  @SerializedName("message" ) var message : String?           = null,
  @SerializedName("result") var result: JsonElement? = null
)

data class LedgerPdfDataShow (
  @SerializedName("LgrAddressId"              ) var LgrAddressId              : String? = null,
  @SerializedName("LgrId"                     ) var LgrId                     : String? = null,
  @SerializedName("StreetAddress"             ) var StreetAddress             : String? = null,
  @SerializedName("City"                      ) var City                      : String? = null,
  @SerializedName("StateOrProvince"           ) var StateOrProvince           : String? = null,
  @SerializedName("ZipOrPostalCode"           ) var ZipOrPostalCode           : String? = null,
  @SerializedName("Country"                   ) var Country                   : String? = null,
  @SerializedName("TelephoneNos"              ) var TelephoneNos              : String? = null,
  @SerializedName("FaxNos"                    ) var FaxNos                    : String? = null,
  @SerializedName("EmailId1"                  ) var EmailId1                  : String? = null,
  @SerializedName("EmailId2"                  ) var EmailId2                  : String? = null,
  @SerializedName("Website"                   ) var Website                   : String? = null,
  @SerializedName("PanNo"                     ) var PanNo                     : String? = null,
  @SerializedName("TINLSTNo"                  ) var TINLSTNo                  : String? = null,
  @SerializedName("TINCSTNo"                  ) var TINCSTNo                  : String? = null,
  @SerializedName("VATNo"                     ) var VATNo                     : String? = null,
  @SerializedName("ContactPerson1Name"        ) var ContactPerson1Name        : String? = null,
  @SerializedName("ContactPerson1Designation" ) var ContactPerson1Designation : String? = null,
  @SerializedName("ContactPerson2Name"        ) var ContactPerson2Name        : String? = null,
  @SerializedName("ContactPerson2Designation" ) var ContactPerson2Designation : String? = null,
  @SerializedName("InsertedOn"                ) var InsertedOn                : String? = null,
  @SerializedName("LastUpdatedOn"             ) var LastUpdatedOn             : String? = null,
  @SerializedName("InsertedByUserId"          ) var InsertedByUserId          : String? = null,
  @SerializedName("LastUpdatedByUserId"       ) var LastUpdatedByUserId       : String? = null,
  @SerializedName("Range"                     ) var Range                     : String? = null,
  @SerializedName("Division"                  ) var Division                  : String? = null,
  @SerializedName("ECCNo"                     ) var ECCNo                     : String? = null,
  @SerializedName("ECCDt"                     ) var ECCDt                     : String? = null,
  @SerializedName("IEC"                       ) var IEC                       : String? = null,
  @SerializedName("Commissionerate"           ) var Commissionerate           : String? = null,
  @SerializedName("DefNatOfPur"               ) var DefNatOfPur               : String? = null,
  @SerializedName("NatOfRem"                  ) var NatOfRem                  : String? = null,
  @SerializedName("NotiNo"                    ) var NotiNo                    : String? = null,
  @SerializedName("VATDealType"               ) var VATDealType               : String? = null,
  @SerializedName("VATRegDt"                  ) var VATRegDt                  : String? = null,
  @SerializedName("CSTRegDt"                  ) var CSTRegDt                  : String? = null,
  @SerializedName("ACNo"                      ) var ACNo                      : String? = null,
  @SerializedName("BranchName"                ) var BranchName                : String? = null,
  @SerializedName("BSRCode"                   ) var BSRCode                   : String? = null,
  @SerializedName("BankName"                  ) var BankName                  : String? = null,
  @SerializedName("ContactPerson1MobileNo"    ) var ContactPerson1MobileNo    : String? = null,
  @SerializedName("ContactPerson2MobileNo"    ) var ContactPerson2MobileNo    : String? = null,
  @SerializedName("GSTNo"                     ) var GSTNo                     : String? = null,
  @SerializedName("BankAddress"               ) var BankAddress               : String? = null,
  @SerializedName("AccNo"                     ) var AccNo                     : String? = null,
  @SerializedName("IFSCCode"                  ) var IFSCCode                  : String? = null,
  @SerializedName("AccountName"               ) var AccountName               : String? = null,
  @SerializedName("MobileNo"                  ) var MobileNo                  : String? = null,
  @SerializedName("ProductName"               ) var ProductName               : String? = null,
  @SerializedName("Branch"                    ) var Branch                    : String? = null,
  @SerializedName("ChequeNo"                  ) var ChequeNo                  : String? = null,
  @SerializedName("Limit"                     ) var Limit                     : String? = null,
  @SerializedName("Amount"                    ) var Amount                    : String? = null,
  @SerializedName("CityId"                    ) var CityId                    : String? = null,
  @SerializedName("StateId"                   ) var StateId                   : String? = null,
  @SerializedName("CountryId"                 ) var CountryId                 : String? = null,
  @SerializedName("Disc"                      ) var Disc                      : String? = null,
  @SerializedName("AadharNo"                  ) var AadharNo                  : String? = null,
  @SerializedName("GSTPartyTypeTextListId"    ) var GSTPartyTypeTextListId    : String? = null,
  @SerializedName("TalukaId"                  ) var TalukaId                  : String? = null,
  @SerializedName("DistrictId"                ) var DistrictId                : String? = null,
  @SerializedName("AddressType"               ) var AddressType               : String? = null,
  @SerializedName("IsExcise"                  ) var IsExcise                  : String? = null,
  @SerializedName("EmailIdFirst"              ) var EmailIdFirst              : String? = null,
  @SerializedName("EmailIdSecond"             ) var EmailIdSecond             : String? = null,
  @SerializedName("MobileNoFirst"             ) var MobileNoFirst             : String? = null,
  @SerializedName("MobileNoSecond"            ) var MobileNoSecond            : String? = null,
  @SerializedName("VillageName"               ) var VillageName               : String? = null,
  @SerializedName("VillageCode"               ) var VillageCode               : String? = null,
  @SerializedName("Taluka"                    ) var Taluka                    : String? = null,
  @SerializedName("District"                  ) var District                  : String? = null,
  @SerializedName("Route"                     ) var Route                     : String? = null,
  @SerializedName("GSTTypeId"                 ) var GSTTypeId                 : String? = null,
  @SerializedName("RTGSCode"                  ) var RTGSCode                  : String? = null,
  @SerializedName("PhoneNo2"                  ) var PhoneNo2                  : String? = null,
  @SerializedName("Area"                      ) var Area                      : String? = null,
  @SerializedName("IsDefault"                 ) var IsDefault                 : String? = null,
  @SerializedName("ShowAging"                 ) var ShowAging                 : String? = null,
  @SerializedName("PayOrRec"                  ) var PayOrRec                  : String? = null,
  @SerializedName("ShowPDF"                   ) var ShowPDF                   : String? = null

)